api_tests start_tests_server script: exit with an error if the entities search engine service isn't online

diff --git a/api_tests/scripts/start_tests_server b/api_tests/scripts/start_tests_server
--- a/api_tests/scripts/start_tests_server
+++ b/api_tests/scripts/start_tests_server
@@ -1,14 +1,21 @@
 #!/usr/bin/env zsh
 
-testhost=http://localhost:3009
+export NODE_ENV=tests FORCE_COLOR=true
+
+test_host=$(node -p "require('config').fullHost()")
+entities_search_engine_host=$(node -p "require('config').entitiesSearchEngine.host")
+
+curl -s "$entities_search_engine_host" > /dev/null && echo "entities search engine found" || \
+  # Using curly brackets to group those commands without starting a subshell from which exiting would be useless
+  # cf https://ss64.com/bash/syntax-brackets.html
+  { echo "entities search engine not found at ${entities_search_engine_host}" && exit 1; }
 
 # If the server is already up, return early
-(curl -s "$testhost" > /dev/null || [ "$(cat run/3009)" == "starting" ]) &&
+(curl -s "$test_host" > /dev/null || [ "$(cat run/3009)" == "starting" ]) &&
 echo "server already started" &&
 exit 0
 
 # Start a test server in the background
-export NODE_ENV=tests FORCE_COLOR=true
 npm run watch > logs/test-server.log 2>&1 &
 
 # Will be replaced by the process pid once the server started
