harmonize case: replace ElasticSearch by Elasticsearch

diff --git a/scripts/postinstall b/scripts/postinstall
--- a/scripts/postinstall
+++ b/scripts/postinstall
@@ -27,13 +27,13 @@ touch run/3006 run/3009
 # Expected by scripts/entities_indexation
 mkdir -p scripts/entities_indexation/queries/sparql scripts/entities_indexation/queries/results
 
-# Synchronize CouchDB and ElasticSearch databases
+# Synchronize CouchDB and Elasticsearch databases
 {
   elastic_host=$(node -p "require('config').elasticsearch.host")
   curl -s $elastic_host > /dev/null &&
-  echo "Found ElasticSearch" &&
+  echo "Found Elasticsearch" &&
   npm run couch2elastic4sync:init && npm run couch2elastic4sync:load
-} || echo "ElasticSearch not found: init & load scripts skipped"
+} || echo "Elasticsearch not found: init & load scripts skipped"
 
 [ -z ./config/local.js ] && {
   # Create a local config file
